In [102]:
from __future__ import division
import numpy as np
from scipy import linalg as la
import matplotlib.pyplot as plt
%matplotlib inline

In [152]:
def projection(v,u):
    return ((v.dot(u))/(u.dot(u)))*u

def vector_unit(v):
    return v/np.sqrt(v.dot(v))

#### Problem 3

In [132]:
v_project = np.array([-4,-2,3,1.2,-5.5,8.8,-1.9])
s1 = np.array([1,1,3,1,-1,-3,9])
s2 = np.array([1,-2,3,1,-1,4,-3])

In [140]:
v_k = v_project
v1 = s1
v2 = s2

In [141]:
u1 = s1
u2 = v2-projection(v2,u1)

In [143]:
u3 = v_k - projection(v_k,u1) - projection(v_k,u2)

In [151]:
u3

array([-5.50952099,  0.79231224, -1.52856298, -0.30952099, -3.99047901,
        3.2909521 ,  1.721644  ])

#### Problem 4

In [208]:
A = np.matrix([[-4,1,1],[-2,-2,1],[3,-10,4]])
eigvals,eigvecs = np.linalg.eig(A)

In [209]:
eigvecs_a = np.array(eigvecs)

In [210]:
eigvals*eigvecs_a

array([[ 0.07175536+1.63413753j,  0.07175536-1.63413753j,  0.48856061+0.j        ],
       [-0.88930480+1.42423762j, -0.88930480-1.42423762j,  0.40910127+0.j        ],
       [-1.63505539+1.02092163j, -1.63505539-1.02092163j,  3.08340399+0.j        ]])

In [211]:
A*eigvecs_a

matrix([[ 0.07175536+1.63413753j,  0.07175536-1.63413753j,  0.48856061+0.j        ],
        [-0.88930480+1.42423762j, -0.88930480-1.42423762j,  0.40910127+0.j        ],
        [-1.63505539+1.02092163j, -1.63505539-1.02092163j,  3.08340399+0.j        ]])

In [215]:
print (A-eigvals*np.identity(3))*eigvecs_a

[[ -5.55111512e-16 +2.77555756e-16j   1.50852058e+00 -8.52306344e-01j
    8.88010415e-01 -2.49414757e-01j]
 [  7.80755880e-01 +1.59805692e+00j  -1.11022302e-16 -1.11022302e-16j
    7.43584681e-01 +2.08850020e-01j]
 [ -3.63486526e+00 +1.02092163e+00j  -3.63486526e+00 -1.02092163e+00j
   -1.99840144e-15 +0.00000000e+00j]]


In [281]:
ttA = np.matrix([[-1,2,2],[2,2,-1],[2,-1,2]])

In [282]:
ttA_inv = ttA**-1

In [283]:
ttA_inv

matrix([[-0.11111111,  0.22222222,  0.22222222],
        [ 0.22222222,  0.22222222, -0.11111111],
        [ 0.22222222, -0.11111111,  0.22222222]])

In [284]:
ttA

matrix([[-1,  2,  2],
        [ 2,  2, -1],
        [ 2, -1,  2]])

In [285]:
tteval,ttevec = np.linalg.eig(ttA)
tteval_inv,ttevec_inv = np.linalg.eig(ttA_inv)

In [291]:
tteval

array([-3.,  3.,  3.])

In [328]:
ttA

matrix([[-1,  2,  2],
        [ 2,  2, -1],
        [ 2, -1,  2]])

In [329]:
ttA_inv

matrix([[-0.11111111,  0.22222222,  0.22222222],
        [ 0.22222222,  0.22222222, -0.11111111],
        [ 0.22222222, -0.11111111,  0.22222222]])

In [335]:
tteval_inv

array([-0.33333333,  0.33333333,  0.33333333])

In [336]:
1/(1-tteval)

array([ 0.25, -0.5 , -0.5 ])

In [326]:
ttevec

matrix([[-0.81649658,  0.57735027, -0.27602622],
        [ 0.40824829,  0.57735027, -0.89708523],
        [ 0.40824829,  0.57735027,  0.34503278]])

In [295]:
tteval_inv*np.array(ttA)

array([[ 0.33333333,  0.66666667,  0.66666667],
       [-0.66666667,  0.66666667, -0.33333333],
       [-0.66666667, -0.33333333,  0.66666667]])

In [299]:
ttA*ttevec_inv

matrix([[ 2.44948974,  1.73205081,  0.63752422],
        [-1.22474487,  1.73205081, -1.33487136],
        [-1.22474487,  1.73205081,  2.60991979]])

In [300]:
ttA_inv*ttevec_inv

matrix([[ 0.27216553,  0.19245009,  0.07083602],
        [-0.13608276,  0.19245009, -0.14831904],
        [-0.13608276,  0.19245009,  0.28999109]])

In [303]:
ttevec_inv.dot(ttevec)

matrix([[ 0.98912498, -0.01537959, -0.21923568],
        [-0.27928406,  0.31213948, -0.78414442],
        [ 0.25753402,  1.07131489, -0.33045034]])